export const project_list = [
  {
    name: "jg collab (Miro board clone)",
    date: "2024",
    github: "https://github.com/AyushJG/JG-Collab",
    go: "https://jg-collab.vercel.app/",
    description: [
      "This is a miro board clone named after my nickname JG-Collab. ",
      "It is a web application that allows users to create and collaborate on boards.",
    ],
    domains: ["Typescript", "Next.js", "Tailwind css", "ReactJS", "ShadcnUI"],
  },
  {
    name: "jg-resume-builder",
    date: "2024",
    github: "https://github.com/AyushJG/jg-resume-builder",
    go: "https://jg-resume-builder.onrender.com/",
    description: [
      " Easy and convenient resume builder made using next and react js. ",
    ],
    domains: [
      "HTML",
      "CSS",
      "Typescript",
      "ReactJS",
      "Next JS",
      "Redux",
      "Formik",
      "Yup",
    ],
  },
  {
    name: "course-nepal",
    date: "2024",
    github: "https://github.com/AyushJG/course-nepal",
    go: "https://course-nepal.onrender.com/",
    description: [
      "This project involves designing a concept page for a course-selling website. ",
      "The primary objective is to enhance my skills in Material-UI, Next.js, and TypeScript.",
    ],
    domains: ["HTML", "CSS", "Typescript", "ReactJS", "Material-Ui"],
  },
  {
    name: "Cheesy-bites",
    date: "2024",
    github: "https://github.com/AyushJG/cheesy-bites",
    go: "https://ayushjg.github.io/cheesy-bites/",
    description: ["This is a Ecommerce Food delivery web application."],
    domains: ["Bootstrap", "ReactJS", "Redux"],
  },

  {
    name: "Ayush Portfolio",
    date: "2024",
    github: "https://github.com/AyushJG",
    go: "https://ayushjg.github.io/AyushJG/",
    description: [
      "Personal portfolio website of theme Random OS, made using NEXT.js & tailwind CSS",
    ],
    domains: ["HTML", "CSS", "Javascript"],
  },
  {
    name: "jg-chess",
    date: "2024",
    github: "https://github.com/AyushJG/jg-chess",
    go: "https://ayushjg.github.io/jg-chess/",
    description: [
      "This is a offline chess game made using typescript as a summer project.",
    ],
    domains: ["HTML", "CSS", "Typescript", "ReactJS", "Vite"],
  },
  {
    name: "chasma-pasal (glasses store)",
    date: "2023",
    github: "https://github.com/AyushJG/chasma-pasal",
    go: "https://ayushjg.github.io/chasma-pasal/",
    description: ["This is a B2C eccomerce website for buying glasses online."],
    domains: ["ReactJS", "Vite", "Tailwind css ", "HTML", "CSS", "Javascript"],
  },
  {
    name: "hangman",
    date: "2023",
    github: "https://github.com/AyushJG/hangman",
    go: "https://ayushjg.github.io/hangman/",
    description: [
      "It's a fun game to play where you have to guess the word by guessing the letters.",
    ],
    domains: ["HTML", "CSS", "Javascript"],
  },
  {
    name: "Tic-tac-toe",
    date: "2022",
    github: "https://github.com/AyushJG/Tic-tac-toe",
    go: "https://ayushjg.github.io/Tic-tac-toe/",
    description: [
      "It's a Tic-tac-toe which is a two-player game played on a 3x3 grid. ",
      "The objective of the game is to be the first player to get three of their marks in a row, either horizontally, vertically, or diagonally.",
    ],
    domains: ["HTML", "CSS", "Javascript"],
  },
  {
    name: "Pujamandu",
    date: "2020",
    github: "https://pujamandu.com/",
    go: "https://pujamandu.com/",
    description: [
      "This is a ecommerce website for purchasing religious services online.",
    ],
    domains: ["HTML", "CSS", "Javascript"],
  },
];

export const tag_colors = {
  javascript: "yellow-300",
  firebase: "red-600",
  firestore: "red-500",
  "firebase auth": "red-400",
  "chrome-extension": "yellow-400",
  flutter: "blue-400",
  dart: "blue-500",
  "react-native": "purple-500",
  html5: "pink-600",
  sass: "pink-400",
  tensorflow: "yellow-600",
  django: "green-600",
  python: "green-200",
  "codeforces-api": "gray-300",
  tailwindcss: "blue-300",
  "next.js": "purple-600",
};
